name: pages-update
run-name: pages update from main repo

on:
  repository_dispatch:
    types: [update]

jobs:
  update_dist:
    name: update-push
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Release download
        uses: robinraju/release-downloader@v1.5
        with:
          repository: "searchmarkers/mark-my-search"
          latest: true
          fileName: "mark_my_search-firefox.zip"
          out-file-path: releases
      - name: Release extract
        run: unzip releases/mark_my_search-firefox.zip -d releases/mark_my_search-firefox
      - name: Artifact archive dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "releases/mark_my_search-firefox/dist"
      - name: Update commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/searchmarkers/searchmarkers.github.io
          cp -r releases/mark_my_search-firefox/dist/ searchmarkers.github.io/
          FILES="releases/mark_my_search-firefox/pages/*"
          for file_path in $FILES
          do
            file_fullname="${file_path##*/}"
            file_name="${file_fullname%.*}"
            mkdir --parents searchmarkers.github.io/pages/$file_name/
            mv $file_path searchmarkers.github.io/pages/$file_name/index.html
          done
          cd searchmarkers.github.io
          cat polyfill.js dist/manage-storage.js > temp
          cat temp > dist/manage-storage.js
          rm temp
          git config user.name "searchmarkers"
          git config user.email "dev@example.com"
          if [ -z "$( git status --short )" ]
          then
            echo "nothing to commit"
          else
            git add .
            git commit -m "Update dist"
            git push
          fi
      - name: Artifact archive pages
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: "releases/mark_my_search-firefox/pages"
