name: Compile Source
run-name: ${{ github.actor }} is compiling source files

on: [repository_dispatch]

jobs:
  update_dist:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: a
      uses: robinraju/release-downloader@v1.5
      with:
        repository: "searchmarkers/mark-my-search"
        latest: true
        fileName: "mark_my_search-firefox.zip"
        out-file-path: releases
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: releases/mark_my_search-firefox/dist
        path: dist
